services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conggiasu-app
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
      # - redis
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  # redis:
  #   image: redis:7-alpine
  #   container_name: nestjs-redis
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   networks:
  #     - app-network
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
